# Generated by Django 5.2.4 on 2025-10-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Us', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('stat1_number', models.CharField(blank=True, max_length=20)),
                ('stat1_label', models.CharField(blank=True, max_length=100)),
                ('stat2_number', models.CharField(blank=True, max_length=20)),
                ('stat2_label', models.CharField(blank=True, max_length=100)),
                ('stat3_number', models.CharField(blank=True, max_length=20)),
                ('stat3_label', models.CharField(blank=True, max_length=100)),
                ('stat4_number', models.CharField(blank=True, max_length=20)),
                ('stat4_label', models.CharField(blank=True, max_length=100)),
                ('mission_title', models.CharField(blank=True, max_length=200)),
                ('mission_description', models.TextField(blank=True)),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/mvv/')),
                ('vision_title', models.CharField(blank=True, max_length=200)),
                ('vision_description', models.TextField(blank=True)),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='about/mvv/')),
                ('values_title', models.CharField(blank=True, max_length=200)),
                ('values_description', models.TextField(blank=True)),
                ('values_image', models.ImageField(blank=True, null=True, upload_to='about/mvv/')),
                ('cta_primary_label', models.CharField(blank=True, max_length=60)),
                ('cta_primary_href', models.CharField(blank=True, max_length=200)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=60)),
                ('cta_secondary_href', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_href', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='JourneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_entries', to='sitecontent.aboutsection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatwedo_items', to='sitecontent.aboutsection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
