# Generated by Django 5.2.4 on 2025-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('tag_color', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='programs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
