# Generated by Django 5.2.4 on 2025-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='STORY', max_length=40)),
                ('tag_color', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('desc', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='stories/')),
                ('href', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
