# Generated by Django 5.2.4 on 2025-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_contactinfo_delete_contactsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='points',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='point_one',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='point_three',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='point_two',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='highlight_words',
            field=models.CharField(blank=True, default='', help_text='Comma-separated highlight words', max_length=200),
        ),
    ]
