# Generated by Django 5.2.4 on 2025-10-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_remove_aboutsection_points_aboutsection_point_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='highlight_words',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='point_one',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='point_three',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='point_two',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
